### ISSUE TITLE
Fail to deploy core.war over WildFly

### ISSUE THREAD

**Issue by driftyz700** [SoapboxRaceWorld/soapbox-race-core#61]
server fails to deploy when used over wildfly 19.0.0 (have tried older versions as well but the error is the same).

{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"core.war\".component.OpenFireSoapBoxCli.START" => "java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBTransactionRolledbackException
    Caused by: java.lang.NullPointerException"}}

**Comment by driftyz700** [comment]
Update: I have openfire 4.5.1 running on the same host with nosaslauthentication and sbrw restapi plugins loaded and configured. XMPP domain is set to 127.0.0.1 and core server seems to be able to attempt to connect but throws this error in console followed by the error above.

ERROR [org.jboss.as.ejb3.invocation] (ServerService Thread Pool -- 82) WFLYEJB0034: EJB Invocation failed on component OpenFireConnector for method public void com.soapboxrace.core.xmpp.OpenFireConnector.connect(): javax.ejb.EJBTransactionRolledbackException
	at org.jboss.as.ejb3@19.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:215)
	at org.jboss.as.ejb3@19.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:376)
	at org.jboss.as.ejb3@19.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:156)
	at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
