### ISSUE TITLE
CarSlotBO.scheduledRemoval task throws transaction errors

### ISSUE THREAD

**Issue by LeoCodes21** [SoapboxRaceWorld/soapbox-race-core#77]
```
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: Caused by: javax.persistence.PersistenceException: org.hibernate.HibernateException: Transaction was rolled back in a different thread!
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: at org.hibernate@5.3.13.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: at org.hibernate@5.3.13.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1515)
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: at org.hibernate@5.3.13.Final//org.hibernate.query.Query.getResultList(Query.java:132)
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: at deployment.core.war//com.soapboxrace.core.dao.CarSlotDAO.findAllExpired(CarSlotDAO.java:58)
...
Nov 14 18:18:00 xxxxxxxxxxxx.privatedns.com game-server[yyyyy]: at deployment.core.war//com.soapboxrace.core.bo.CarSlotBO.scheduledRemoval(CarSlotBO.java:37)
```

This issue seems to stem from the fact that `CarSlotBO` is annotated with the `@Stateless` annotation. All other classes with scheduled tasks are singleton beans.

**Comment by LeoCodes21** [comment]
This has since been resolved thanks to changes to the database schema.
