### ISSUE TITLE
Achievement processing prone to transaction/locking errors

### ISSUE THREAD

**Issue by LeoCodes21** [SoapboxRaceWorld/soapbox-race-core#78]
```
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
....
    at com.soapboxrace.core.dao.PersonaAchievementDAO$$$view91.findByPersonaIdAndAchievementId
    at com.soapboxrace.core.bo.AchievementBO.updateAchievements(AchievementBO.java:277)
    at com.soapboxrace.core.bo.AchievementBO.lambda$commitTransaction$0(AchievementBO.java:87)
    at java.util.ArrayList.forEach(ArrayList.java:1540)
    at com.soapboxrace.core.bo.AchievementBO.lambda$commitTransaction$1(AchievementBO.java:87)
    at java.util.HashMap.forEach(HashMap.java:1336)
    at com.soapboxrace.core.bo.AchievementBO.commitTransaction(AchievementBO.java:87)
    ....
    at com.soapboxrace.core.bo.CommerceBO$$$view10.doCommerce
    at com.soapboxrace.core.api.Personas.commerce(Personas.java:64)
    ....
javax.ejb.EJBTransactionRolledbackException: could not execute statement
    at com.soapboxrace.core.dao.PersonaAchievementDAO$$$view91.findByPersonaIdAndAchievementId
    at com.soapboxrace.core.bo.AchievementBO.updateAchievements(AchievementBO.java:277)
    at com.soapboxrace.core.bo.AchievementBO.lambda$commitTransaction$0(AchievementBO.java:87)
    at java.util.ArrayList.forEach(ArrayList.java:1540)
    at com.soapboxrace.core.bo.AchievementBO.lambda$commitTransaction$1(AchievementBO.java:87)
    at java.util.HashMap.forEach(HashMap.java:1336)
    at com.soapboxrace.core.bo.AchievementBO.commitTransaction(AchievementBO.java:87)
    at com.soapboxrace.core.bo.CommerceBO.doCommerce(CommerceBO.java:245)
    ....
    at com.soapboxrace.core.api.Personas.commerce(Personas.java:64)
    ....
```

**Comment by LeoCodes21** [comment]
This hasn't been a problem in a while, presumably related to other database issues at the time.
